full_rebuild: true
name: Blog - Cédric Soulas
author: Cédric Soulas
url: https://github.com/cedricss/photon-book-creator
version: 1.0
encoding: utf-8
theme: freelancer
defaults:
  -
    values:
      layout: "index"
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
exclude: [
.git,
.gitignore,
README.md,
LICENSE
]
